let Ouf1= 5;
let Ouf2= 6;

let resultado = Ouf1+Ouf2;
console.log("la suma de Ouf1 + Ouf2 es: " +resultado);

/** 

document.getElementById("Ouff").onclick = function () {

    document.getElementById("demo2").innerHTML = "Mi Dios";
    
}

if (typeof Ouff !== 'null') {
    // Ahora sabemos que foo está definido, ahora podemos continuar.
  }
  
  document.addEventListener("click", function () {

    console.log("Mi dios event listener");
    document.getElementById("demo2").innerHTML = "Mi Dios";
  }
  
  )

  document.getElementById("Ouff").addEventListener("click", function () {

    console.log("Mi dios event listener");
    document.getElementById("demo2").innerHTML = "Mi Dios";
  }
  
  )
*/
  document.getElementById("Ouff").addEventListener("click", function () {

     document.body.style.backgroundColor = "green";
  }
  
  )