let lenght;
var name = Rodolfo;
lenght = 2
console.log (lenght);
// Las variables almacenan datos

Var edad = 20;

if (edad <= 20); {

console.log("No hongos pls");
} else {

    console.log("Vengan esos hongos");
}

var ouf = 12

for (ouf; ouf>7; ouf--)  {

    console.log("el Valor de ouf es" +ouf); // sentencia
}

while (ouf<50) {

    console.log("Hmmmm"+ouf);
    ouf--
    
}

var S = 10;

do {
    console.log("Mi vaina vale:" +S); // Esta es la sentencia
    
} while (S>10);

var ouf = 12

for (ouf; ouf>7; ouf--)  {

    if (ouf ==9 ) {
        break;
    }
    console.log("el Valor de ouf es" +ouf); // sentencia
}

Function  HoynopuedoShifu() {
    console.log("HoynopuedoShifu");
}

HoynopuedoShifu ()

function Sumar(b,c); {
    var resultado = b+c;

    return resultado;

}
Suma Sumar(8,9);
console.log(sum);
